{{- $certManagerNs := (index .Values "cert-manager").namespace }}
{{- $trustManagerNs := (index .Values "trust-manager").namespace }}
{{- if and (eq $certManagerNs $trustManagerNs) (or .Values.installCertManagerComponents .Values.installTrustManagerComponents) }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $certManagerNs }}
  labels:
    name: {{ $certManagerNs }}
{{- end }}
