{{- if .Values.nginx.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx.fullname" . }}-headless
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "nginx.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.nginx.service.port }}
      protocol: TCP
      {{- if .Values.nginx.tls.enabled }}
      targetPort: https
      name: https
      {{- else }}
      targetPort: http
      name: http
      {{- end }}
{{- end }}
