{{- if .Values.test.enabled }}
apiVersion: v1
kind: Pod
metadata:
  name: "{{ include "squid.fullname" . }}-test"
  namespace: {{ .Values.namespace.name }}
  labels:
    # Use different app name to avoid service selector conflicts
    app.kubernetes.io/name: squid
    app.kubernetes.io/instance: {{ include "squid.fullname" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: test
    app: {{ .Values.test.name }}
    helm.sh/chart: {{ include "squid.chart" . }}
  annotations:
    "helm.sh/hook": test
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  restartPolicy: Never
  serviceAccountName: {{ include "squid.fullname" . }}-test
  containers:
  - name: ginkgo-test
    image: "{{ include "squid.test.image" . }}"
    imagePullPolicy: {{ .Values.test.image.pullPolicy | default "IfNotPresent" }}
    workingDir: /app
    command:
    - /app/test-entrypoint.sh
    env:
    - name: TARGET_NAMESPACE
      value: {{ .Values.namespace.name | quote }}
    - name: SQUID_SERVICE
      value: "{{ include "squid.fullname" . }}.{{ .Values.namespace.name }}.svc.cluster.local:{{ .Values.service.port }}"
    - name: LABEL_FILTER
      value: {{ .Values.test.labelFilter | quote }}
    # Pass environment to test binary so it knows which image repos to use
    - name: SQUID_ENVIRONMENT
      value: {{ .Values.environment | quote }}
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    resources:
      {{- toYaml .Values.test.resources | nindent 6 }}
{{- end }}
