{{- if .Values.test.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "squid.fullname" . }}-test
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "squid.labels" . | nindent 4 }}
    app.kubernetes.io/component: test
  {{- if not .Values.mirrord.enabled }}
  annotations:
    "helm.sh/hook": test
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "squid.fullname" . }}-test
  labels:
    {{- include "squid.labels" . | nindent 4 }}
    app.kubernetes.io/component: test
  {{- if not .Values.mirrord.enabled }}
  annotations:
    "helm.sh/hook": test
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  {{- end }}
rules:
# Expansive permissions are required to run `helm upgrade` from inside the test pod.
- apiGroups: [""]
  resources: ["namespaces", "pods", "services", "endpoints", "secrets", "configmaps", "serviceaccounts"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterroles", "clusterrolebindings", "roles", "rolebindings"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "daemonsets", "statefulsets"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations", "validatingwebhookconfigurations"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
- apiGroups: ["monitoring.coreos.com"]
  resources: ["servicemonitors"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
- apiGroups: ["cert-manager.io"]
  resources: ["certificates", "clusterissuers", "issuers"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
- apiGroups: ["trust.cert-manager.io"]
  resources: ["bundles"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
- apiGroups: [""]
  resources: ["pods/log", "pods/exec"]
  verbs: ["get", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "squid.fullname" . }}-test
  labels:
    {{- include "squid.labels" . | nindent 4 }}
    app.kubernetes.io/component: test
  {{- if not .Values.mirrord.enabled }}
  annotations:
    "helm.sh/hook": test
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "squid.fullname" . }}-test
subjects:
- kind: ServiceAccount
  name: {{ include "squid.fullname" . }}-test
  namespace: {{ .Values.namespace.name }}
{{- end }}
