{{- if .Values.installTrustManagerComponents }}
{{- $certManagerNs := (index .Values "cert-manager").namespace }}
{{- $trustManagerNs := (index .Values "trust-manager").namespace }}
{{- if ne $certManagerNs $trustManagerNs }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $trustManagerNs }}
  labels:
    name: {{ $trustManagerNs }}
{{- end }}
{{- end }}
