{{- if (index .Values "selfsigned-bundle").enabled }}
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: {{ .Values.namespace.name }}-ca-bundle
  labels:
    {{- include "squid.labels" . | nindent 4 }}
spec:
  sources:
  - secret:
      name: "{{ .Values.namespace.name }}-root-ca-secret"
      key: "ca.crt"
  target:
    configMap:
      key: "ca-bundle.crt"
    namespaceSelector:
      {{- $envSettings := index .Values.envSettings .Values.environment }}
      {{- toYaml (index $envSettings.squid "trust-manager" "namespaceSelector") | nindent 6 }}
{{- end }}
