version: "2"
run:
  timeout: 5m
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - dupl
    - errcheck
    - ginkgolinter
    - goconst
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    revive:
      rules:
        - name: comment-spacings
        - name: import-shadowing
  exclusions:
    generated: lax
    rules:
      - linters:
          - lll
        path: _test\.go
      - linters:
          - dupl
          - errcheck
        path: _test\.go
      - linters:
          - unused
        path: tools\.go
    paths:
      - third_party$
      - builtin$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
