{{- if .Values.nginx.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "caching.nginx.namespace" . }}
  labels:
    name: {{ include "caching.nginx.namespace" . }}
{{- with .Values.nginx.namespaceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
