{{- if and .Values.squid.enabled (index .Values "selfsigned-certificate").enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "caching.squid.namespace" . }}-cert
  namespace: {{ include "caching.squid.namespace" . }}
spec:
  isCA: true
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  subject:
    organizations:
      - konflux
  dnsNames:
  - localhost
  - {{ .Values.squid.name }}
  - {{ .Values.squid.name }}.{{ include "caching.squid.namespace" . }}.svc
  - {{ .Values.squid.name }}.{{ include "caching.squid.namespace" . }}.svc.cluster.local

  issuerRef:
    kind: ClusterIssuer
    name: {{ include "caching.squid.namespace" . }}-ca-issuer
  secretName: {{ include "caching.squid.namespace" . }}-tls
{{- end }}
