{{- if or .Values.squid.enabled .Values.test.enabled .Values.mirrord.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "caching.squid.namespace" . }}
  labels:
    name: {{ include "caching.squid.namespace" . }}
{{- with .Values.squid.namespaceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
