{{- if and .Values.squid.enabled (index .Values "selfsigned-bundle").enabled }}
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: {{ default (printf "%s-ca-bundle" (include "caching.squid.namespace" .)) (index .Values "selfsigned-bundle").name }}
  labels:
    {{- include "caching.squid.labels" . | nindent 4 }}
spec:
  sources:
  - secret:
      name: "{{ include "caching.squid.namespace" . }}-root-ca-secret"
      key: "ca.crt"
  {{- with (index .Values "selfsigned-bundle").additionalSources }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  target:
    configMap:
      key: "ca-bundle.crt"
    namespaceSelector:
      {{- $envSettings := index .Values.envSettings .Values.environment }}
      {{- toYaml (index $envSettings.squid "trust-manager" "namespaceSelector") | nindent 6 }}
{{- end }}
