name: Go Lint

on:
  push:
    branches: ["main"]
  pull_request:
  merge_group:
    types: [checks_requested]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Install mage
        run: go install "github.com/magefile/mage@$(go list -m -f '{{.Version}}' github.com/magefile/mage)"

      - name: Run golangci-lint
        run: mage lint:go
