name: Go Lint

on:
  pull_request:
  merge_group:
    types: [checks_requested]
  push:
    branches: [ main ]

jobs:
  lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.11.4
