name: Helm Lint

on:
  pull_request:
  merge_group:
    types: [checks_requested]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Set up Helm
        uses: azure/setup-helm@v5

      - name: Lint Caching Helm chart
        run: helm lint caching
